name: CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: labo05_db
          MYSQL_USER: labo05
          MYSQL_PASSWORD: labo05
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Install Python dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is ready"
              exit 0
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL did not become ready in time"
          exit 1

      - name: Seed database schema
        run: mysql -h 127.0.0.1 -uroot -proot < db-init/init.sql

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: "3306"
          DB_NAME: labo05_db
          DB_USER: labo05
          DB_PASSWORD: labo05
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: "6379"
          REDIS_DB: "0"
        run: pytest
